# Generated by Django 4.1.5 on 2023-11-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOOK_TABLE',
            fields=[
                ('book_pk', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=64)),
                ('ISBN_code', models.CharField(blank=True, max_length=32, null=True)),
                ('genre_code', models.CharField(blank=True, max_length=8, null=True)),
                ('hash_note', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LEARNER_TABLE',
            fields=[
                ('learner_pk', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('l_genre_1', models.CharField(blank=True, max_length=32, null=True)),
                ('l_genre_2', models.CharField(blank=True, max_length=32, null=True)),
                ('l_genre_3', models.CharField(blank=True, max_length=32, null=True)),
                ('l_test_banks', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='REVIEW_TABLE',
            fields=[
                ('review_pk', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('reviewr_email', models.CharField(max_length=128)),
                ('score', models.CharField(max_length=8)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TEACHER_TABLE',
            fields=[
                ('teacher_pk', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('t_genre_1', models.CharField(blank=True, max_length=32, null=True)),
                ('t_genre_2', models.CharField(blank=True, max_length=32, null=True)),
                ('t_genre_3', models.CharField(blank=True, max_length=32, null=True)),
                ('t_test_banks', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TEST_TABLE',
            fields=[
                ('test_pk', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=8)),
                ('question', models.CharField(max_length=255)),
                ('ox_answer', models.CharField(blank=True, max_length=8, null=True)),
                ('mt_answer', models.CharField(blank=True, max_length=8, null=True)),
                ('sa_answer', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TESTBANK_TABLE',
            fields=[
                ('test_bank_pk', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('book_pk', models.CharField(max_length=8)),
                ('test_bank_name', models.CharField(max_length=64)),
                ('score', models.CharField(max_length=64)),
                ('test_keys', models.CharField(max_length=255)),
                ('review_keys', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='USER_TABLE',
            fields=[
                ('email', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
                ('nickname', models.CharField(blank=True, max_length=64, null=True)),
                ('learner_pk', models.CharField(max_length=32)),
                ('teacher_pk', models.CharField(max_length=32)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
