# Generated by Django 4.1.5 on 2023-11-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbank_table',
            name='genre_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
